#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Feb 06 17:30:18 WET 2023
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto bb6307f7bb2346d2990ff04cb8c6c518 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_tob_1_behav xil_defaultlib.tb_tob_1 xil_defaultlib.glbl -log elaborate.log"
xelab -wto bb6307f7bb2346d2990ff04cb8c6c518 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_tob_1_behav xil_defaultlib.tb_tob_1 xil_defaultlib.glbl -log elaborate.log

